 apiVersion: v1
 kind: Service
 metadata:
   annotations:
     service.alpha.openshift.io/serving-cert-secret-name: reversewords-tls
   labels:
     name: reverse-words
   name: reverse-words
 spec:
   ports:
   - name: proxy
     port: 8888
     protocol: TCP
     targetPort: oauth-proxy
   - name: app
     port: 8080
     protocol: TCP
     targetPort: reverse-words
   selector:
     name: reverse-words
   sessionAffinity: None
   type: ClusterIP


